fullnameOverride: squares-api

image:
  repository: maxmorhardt/squares-api
  tag: '0.0.1'
  pullPolicy: Always
  revisionHistoryLimit: 2
  env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-port
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-password
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-name
    - name: DB_SSL_MODE
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: db-ssl-mode
    - name: REDIS_HOST
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: redis-host
    - name: SMTP_HOST
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: smtp-host
    - name: SMTP_PORT
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: smtp-port
    - name: SMTP_USER
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: smtp-user
    - name: SMTP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: smtp-password
    - name: SUPPORT_EMAIL
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: support-email
    - name: JWT_SECRET
      valueFrom:
        secretKeyRef:
          name: squares-api-env
          key: jwt-secret
  readinessProbe:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  livenessProbe:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  name: http

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: squares-api.maxstash.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: squares-api.maxstash.io-tls
      hosts:
        - squares-api.maxstash.io

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 64Mi

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 90
  targetRAM: 90

pdb:
  minAvailable: 1

metrics:
  service:
    type: ClusterIP
    port: 2112
    targetPort: 2112
    name: metrics
