{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingressNamespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    {{- if .Values.metrics.enabled }}
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.service.targetPort }}
    {{- end }}
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        {{- toYaml .Values.networkPolicy.egress.dns.ports | nindent 8 }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.postgresql.port }}
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.redis.port }}
    - to:
        - namespaceSelector: {}
      ports:
        {{- range .Values.networkPolicy.egress.https.ports }}
        - protocol: TCP
          port: {{ . }}
        {{- end }}
{{- end }}
